### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by dieum512** [HERMON-1995/Awesome-books-project#6]
### HIGHLIGHTS 
- [x] No linter errors :+1: 
- [x] Good commit messages :+1: 

### SUGGESTED  CHANGES
-Nice job working on the single page application :+1: , but on whatever page you are, if you refresh the page it is going to take you to the main page, kindly, fix that :wink: 
-Please, add the live demo link to your readme file so that anybody can be able to see the way your project looks without having to clone it :slightly_smiling_face:

**Comment by HERMON-1995** [comment]
Thank you for your insight full review! I will make the necessary changes. 😁
